name: Main

on:
  push:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: echo $ACTIONS_CACHE_URL
      - run: deno run -A index.ts
